version: "3.8"
services:
  fpm-bullseye:
    build:
      dockerfile: fpm.Dockerfile
    image: bahadirbirsoz/phalcon-php:8.2.8-fpm
  bullseye:
    build:
      dockerfile: cli.Dockerfile
    image: bahadirbirsoz/phalcon-php:8.2.8-cli

